In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("healthcare_iot_target_dataset.csv")

In [3]:
df.head()

,Patient_ID,Timestamp,Sensor_ID,Sensor_Type,Temperature (°C),Systolic_BP (mmHg),Diastolic_BP (mmHg),Heart_Rate (bpm),Device_Battery_Level (%),Target_Blood_Pressure,Target_Heart_Rate,Target_Health_Status,Battery_Level (%)
0,8270,2024-01-01 00:00:00,4,Temperature,36.8,150.0,95.0,84.0,99,140.0,90.0,Unhealthy,80
1,1860,2024-01-01 01:00:00,1,Battery,37.3,150.0,95.0,77.0,84,140.0,90.0,Unhealthy,94
2,6390,2024-01-01 02:00:00,1,Temperature,36.5,140.0,85.0,99.0,93,130.0,80.0,Healthy,84
3,6191,2024-01-01 03:00:00,4,Battery,37.3,120.0,80.0,67.0,95,150.0,90.0,Unhealthy,92
4,6734,2024-01-01 04:00:00,4,Temperature,36.8,90.0,60.0,98.0,97,120.0,80.0,Unhealthy,87

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient_ID                200 non-null    int64
 1   Timestamp                 200 non-null    str
 2   Sensor_ID                 200 non-null    int64
 3   Sensor_Type               200 non-null    str
 4   Temperature (°C)          200 non-null    float64
 5   Systolic_BP (mmHg)        200 non-null    float64
 6   Diastolic_BP (mmHg)       200 non-null    float64
 7   Heart_Rate (bpm)          200 non-null    float64
 8   Device_Battery_Level (%)  200 non-null    int64
 9   Target_Blood_Pressure     200 non-null    float64
 10  Target_Heart_Rate         200 non-null    float64
 11  Target_Health_Status      200 non-null    str
 12  Battery_Level (%)         200 non-null    int64
dtypes: float64(6), int64(4), str(3)
memory usage: 20.4 KB

In [5]:
df.duplicated().sum()

np.int64(0)

In [7]:
df = df.drop_duplicates()

In [9]:
df.columns = df.columns.str.strip()

In [11]:
df.rename(columns={
    'Temperature (Â°C)': 'Temperature_C',
    'Systolic_BP (mmHg)': 'Systolic_BP',
    'Diastolic_BP (mmHg)': 'Diastolic_BP',
    'Heart_Rate (bpm)': 'Heart_Rate',
    'Device_Battery_Level (%)': 'Battery_Level'
}, inplace=True)

In [12]:
df.columns

Index(['Patient_ID', 'Timestamp', 'Sensor_ID', 'Sensor_Type',
       'Temperature (°C)', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate',
       'Battery_Level', 'Target_Blood_Pressure', 'Target_Heart_Rate',
       'Target_Health_Status', 'Battery_Level (%)'],
      dtype='str')

In [13]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Patient_ID             200 non-null    int64
 1   Timestamp              200 non-null    datetime64[us]
 2   Sensor_ID              200 non-null    int64
 3   Sensor_Type            200 non-null    str
 4   Temperature (°C)       200 non-null    float64
 5   Systolic_BP            200 non-null    float64
 6   Diastolic_BP           200 non-null    float64
 7   Heart_Rate             200 non-null    float64
 8   Battery_Level          200 non-null    int64
 9   Target_Blood_Pressure  200 non-null    float64
 10  Target_Heart_Rate      200 non-null    float64
 11  Target_Health_Status   200 non-null    str
 12  Battery_Level (%)      200 non-null    int64
dtypes: datetime64[us](1), float64(6), int64(4), str(2)
memory usage: 20.4 KB

In [15]:
df.dtypes

Patient_ID                        int64
Timestamp                datetime64[us]
Sensor_ID                         int64
Sensor_Type                         str
Temperature (°C)                float64
Systolic_BP                     float64
Diastolic_BP                    float64
Heart_Rate                      float64
Battery_Level                     int64
Target_Blood_Pressure           float64
Target_Heart_Rate               float64
Target_Health_Status                str
Battery_Level (%)                 int64
dtype: object

In [18]:
numeric_cols = ['Temperature (°C)', 'Systolic_BP',
                'Diastolic_BP', 'Heart_Rate',
                'Battery_Level']

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [17]:
print(df.columns)

Index(['Patient_ID', 'Timestamp', 'Sensor_ID', 'Sensor_Type',
       'Temperature (°C)', 'Systolic_BP', 'Diastolic_BP', 'Heart_Rate',
       'Battery_Level', 'Target_Blood_Pressure', 'Target_Heart_Rate',
       'Target_Health_Status', 'Battery_Level (%)'],
      dtype='str')

In [19]:
df.isnull().sum()

Patient_ID               0
Timestamp                0
Sensor_ID                0
Sensor_Type              0
Temperature (°C)         0
Systolic_BP              0
Diastolic_BP             0
Heart_Rate               0
Battery_Level            0
Target_Blood_Pressure    0
Target_Heart_Rate        0
Target_Health_Status     0
Battery_Level (%)        0
dtype: int64

In [21]:

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())

In [23]:
df['Sensor_Type'] = df['Sensor_Type'].fillna('Unknown')

In [24]:
df.isnull().sum()

Patient_ID               0
Timestamp                0
Sensor_ID                0
Sensor_Type              0
Temperature (°C)         0
Systolic_BP              0
Diastolic_BP             0
Heart_Rate               0
Battery_Level            0
Target_Blood_Pressure    0
Target_Heart_Rate        0
Target_Health_Status     0
Battery_Level (%)        0
dtype: int64

In [29]:
df = df[(df['Temperature (°C)'] >= 35) & (df['Temperature (°C)'] <= 42)]

In [30]:
df = df[(df['Heart_Rate'] >= 40) & (df['Heart_Rate'] <= 180)]

In [31]:
df = df[(df['Battery_Level'] >= 0) & (df['Battery_Level'] <= 100)]

In [32]:
df.shape

(200, 13)

In [33]:
df = df.sort_values(by='Timestamp')

In [34]:
df.reset_index(drop=True, inplace=True)

In [35]:
df.to_csv("cleaned_healthcare_iot_dataset.csv", index=False)

In [36]:
df.head()

,Patient_ID,Timestamp,Sensor_ID,Sensor_Type,Temperature (°C),Systolic_BP,Diastolic_BP,Heart_Rate,Battery_Level,Target_Blood_Pressure,Target_Heart_Rate,Target_Health_Status,Battery_Level (%)
0,8270,2024-01-01 00:00:00,4,Temperature,36.8,150.0,95.0,84.0,99,140.0,90.0,Unhealthy,80
1,1860,2024-01-01 01:00:00,1,Battery,37.3,150.0,95.0,77.0,84,140.0,90.0,Unhealthy,94
2,6390,2024-01-01 02:00:00,1,Temperature,36.5,140.0,85.0,99.0,93,130.0,80.0,Healthy,84
3,6191,2024-01-01 03:00:00,4,Battery,37.3,120.0,80.0,67.0,95,150.0,90.0,Unhealthy,92
4,6734,2024-01-01 04:00:00,4,Temperature,36.8,90.0,60.0,98.0,97,120.0,80.0,Unhealthy,87

In [37]:
sample_stream = df.head(100)

In [38]:
sample_stream

,Patient_ID,Timestamp,Sensor_ID,Sensor_Type,Temperature (°C),Systolic_BP,Diastolic_BP,Heart_Rate,Battery_Level,Target_Blood_Pressure,Target_Heart_Rate,Target_Health_Status,Battery_Level (%)
0,8270,2024-01-01 00:00:00,4,Temperature,36.800000,150.0,95.0,84.0,99,140.0,90.0,Unhealthy,80
1,1860,2024-01-01 01:00:00,1,Battery,37.300000,150.0,95.0,77.0,84,140.0,90.0,Unhealthy,94
2,6390,2024-01-01 02:00:00,1,Temperature,36.500000,140.0,85.0,99.0,93,130.0,80.0,Healthy,84
3,6191,2024-01-01 03:00:00,4,Battery,37.300000,120.0,80.0,67.0,95,150.0,90.0,Unhealthy,92
4,6734,2024-01-01 04:00:00,4,Temperature,36.800000,90.0,60.0,98.0,97,120.0,80.0,Unhealthy,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8215,2024-01-04 23:00:00,3,Temperature,36.500000,130.0,95.0,81.0,83,120.0,90.0,Unhealthy,84
96,3454,2024-01-05 00:00:00,3,Temperature,37.040556,120.0,80.0,70.0,94,140.0,80.0,Healthy,91
97,9996,2024-01-05 01:00:00,2,Temperature,37.040556,130.0,85.0,82.0,99,120.0,80.0,Healthy,90
98,3731,2024-01-05 02:00:00,3,Battery,37.400000,130.0,80.0,60.0,98,120.0,90.0,Healthy,80
99,9154,2024-01-05 03:00:00,2,Temperature,37.000000,90.0,60.0,82.0,82,140.0,90.0,Unhealthy,90

In [39]:
df.to_excel("cleaned_healthcare_iot_dataset.xlsx", index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [40]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [41]:
df.to_excel("cleaned_healthcare_iot_dataset.xlsx", index=False)

In [42]:
import os
os.listdir()

['.zshrc.save',
 '.config',
 'Music',
 'untitled4.py',
 '.zprofile.pysave',
 'cyber',
 'Untitled1.ipynb',
 '.DS_Store',
 'untitled1.py',
 '.CFUserTextEncoding',
 '.xonshrc',
 'untitled5.py',
 'Untitled.ipynb',
 '.zshrc',
 '.local',
 'cleaned_healthcare_iot_dataset.csv',
 'Pictures',
 '.zprofile',
 '.zsh_history',
 '.ipython',
 'Desktop',
 'Library',
 '.matplotlib',
 'Lecture 5_dataset_penguins.csv',
 'iCloud Drive (Archive)',
 'SQL File.code-workspace',
 'Sites',
 'Public',
 '.idlerc',
 '.tcshrc',
 'Lecture5_student_records.csv',
 'healthcare_iot_target_dataset.csv',
 'cleaned_healthcare_iot_dataset.xlsx',
 'Movies',
 'Applications',
 '.profile',
 '.Trash',
 'exp.ipynb',
 'assi.ipynb',
 '.ipynb_checkpoints',
 '.jupyter',
 'Documents',
 'untitled2.py',
 '.vscode',
 '.bash_profile',
 '.swiftpm',
 'untitled6.py',
 'Downloads',
 'healthcare_data_cleaning.ipynb',
 'untitled.py',
 '.zsh_sessions',
 '.conda',
 'untitled3.py']

In [45]:
df['Temperature (°C)'] = df['Temperature (°C)'].round(2)

In [46]:
df.to_excel("cleaned_healthcare_iot_dataset.xlsx", index=False)

In [47]:
import os
os.listdir()

['.zshrc.save',
 '.config',
 'Music',
 'untitled4.py',
 '.zprofile.pysave',
 'cyber',
 'Untitled1.ipynb',
 '.DS_Store',
 'untitled1.py',
 '.CFUserTextEncoding',
 '.xonshrc',
 'untitled5.py',
 'Untitled.ipynb',
 '.zshrc',
 '.local',
 'cleaned_healthcare_iot_dataset.csv',
 'Pictures',
 '.zprofile',
 '.zsh_history',
 '.ipython',
 'Desktop',
 'Library',
 '.matplotlib',
 'Lecture 5_dataset_penguins.csv',
 'iCloud Drive (Archive)',
 'SQL File.code-workspace',
 'Sites',
 'Public',
 '.idlerc',
 '.tcshrc',
 'Lecture5_student_records.csv',
 'healthcare_iot_target_dataset.csv',
 'cleaned_healthcare_iot_dataset.xlsx',
 'Movies',
 'Applications',
 '.profile',
 '.Trash',
 'exp.ipynb',
 'assi.ipynb',
 '.ipynb_checkpoints',
 '.jupyter',
 'Documents',
 'untitled2.py',
 '.vscode',
 '.bash_profile',
 '.swiftpm',
 'untitled6.py',
 'Downloads',
 'healthcare_data_cleaning.ipynb',
 'untitled.py',
 '.zsh_sessions',
 '.conda',
 'untitled3.py']

In [48]:
df.to_csv("cleaned_healthcare_iot_dataset.csv", index=False)